### ISSUE TITLE
Usage help

### ISSUE THREAD

**Issue by UltraBlackLinux** [Teascade/pipeswitch#8]
Hey there,
I just found this project, and it solves some issues I've been dealing with for a while, but I just can't for the life of me get this to work.

I tried to follow the sparse documentation as far as possible, but nothing is connecting.

This is my current config:
```toml
[general]
linger_links = false
hotreload_config = true

[log]
# trace / debug / info / warn / error
level = "info"

[bluez_card.00_1B_66_E8_CB_52] # I guess this line is where the issue resides. What is the node?
source = "alsa_input.usb-Yamaha_Corporation_Yamaha_MX_Series-00.iec958-stereo"
sink = "bluez_output.00_1B_66_E8_CB_52.1"
special_empty_ports = true
```
The following are the in- and outputs of the corresponding nodes:
```
Out:
alsa_input.usb-Yamaha_Corporation_Yamaha_MX_Series-00.iec958-stereo:capture_FL
alsa_input.usb-Yamaha_Corporation_Yamaha_MX_Series-00.iec958-stereo:capture_FR

In:
bluez_output.00_1B_66_E8_CB_52.1:playback_FL
bluez_output.00_1B_66_E8_CB_52.1:playback_FR
```

What do I need to do? I don't understand.
Thanks!

**Comment by Teascade** [comment]
This is certainly a good example why it probably would be a good idea to try and match node-names exactly as well as using regular expressions. 

In this particular case I think the issue lies with RegEx syntax. Source/Sink are currently only read as RegEx, so as you've input the whole name of the nodes (including dots) into the sink and source.

I would see if you have any luck using something like
```toml
source = ".*Yamaha_Corporation_Yamaha_MX_Series.*"
sink = ".*bluez_output.*"
```

You can try to use https://regexr.com/ to preview what kinds of symbols can have special meanings in regex. `.` is among those, and I think that might be causing the issue here.

Also, `special_empty_ports` is `true` by default so you don't need to specify that, if you like :)

**Comment by Teascade** [comment]
Oh two things new things actually after reading the issue even further;

The issue might not actually be in the RegEx, but actually the header itself should not contain dots. I should probably mention about this in the readme if I can find a source that would definitively declare what symbols you can use for headers, but periods actually have a semantic meaning in TOML that will probably make the config not work as intended. So another thing I would actually try even before my earlier suggestion is to rename the header as simply `[bluez_card]`

------
Another thing I realized you had asked;
> What is the node?

Another tool you can actually use to preview specifically the nodes/etc. exist within your system aside from `pw-link` is actually `pw-dump`. It gives a lot of information you probably don't need, but it gives a more "perfect" preview of what you're actually working with.

**Comment by UltraBlackLinux** [comment]
I just applied these changes and for some reason it still does not work.

I still think this is related to the node issue. I took a look at `pw-dump` but I still don't know what to look for. Is the node you are referring to the `node.id` or the `node.name`? What is it? The directions are rather unclear to me

**Comment by Teascade** [comment]
`node.name` is the one that's being used for regex comparison. What does the config file look like now then?

**Comment by UltraBlackLinux** [comment]
Okay, seems like I was a little confused about the toml block name. I thought that was relevant for some detection too.

Anyways, this is still not working. I double-checked all the names and I'm out of ideas:

```toml
[link.keybord-to-350bt]
source = ".*Yamaha_Corporation_Yamaha_MX_Series.*"
sink = ".*00_1B_66_E8_CB_52.*"
```
